# Generated by Django 4.1.3 on 2022-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0004_remove_trait_pets"),
        ("pets", "0002_pet_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
